on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: { }

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: "write"
  pages: "write"
  id-token: "write"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:

    runs-on: "ubuntu-latest"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    steps:
      # Prepare
      - uses: "actions/checkout@v4"
        with:
          lfs: "true"
      - run: "pip install poetry"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
          cache: "poetry"
      - run: "poetry install"

      # Build
      - run: "printf 'YACV_DISABLE_SERVER=True\nexport_yacv=True\nexport_step=True\nexport_stl=True\n' >> $GITHUB_ENV"
      - run: "poetry run python main.py"
      - run: "final=True poetry run python main.py"
      - run: "mkdir export && mv *.glb *.stl *.step export/"

      # Deploy
      - uses: "actions/configure-pages@v5"
      - uses: "actions/upload-pages-artifact@v3"
        with:
          path: 'export'
      - id: "deployment"
        uses: "actions/deploy-pages@v4"